#!/bin/bash

cd $WTOOL_DIR && git pull
for folder in `ls -l $WTOOL_DIR/custom |grep ^d |awk '{print $9}'` ;do
    if [ ! -d $WTOOL_DIR/$folder/tools ]; then
	continue;
    fi
    cd $WTOOL_DIR/$folder && git pull
done

