#!/bin/bash

echo "update wtool ..."
cd $WTOOL_DIR && git pull
for folder in `ls -l $WTOOL_DIR/custom |grep ^d |awk '{print $9}'` ;do
    if [ ! -d $WTOOL_DIR/custom/$folder/tools ]; then
	continue;
    fi
    echo "update wtool/custom/$folder ..."
    cd $WTOOL_DIR/custom/$folder && git pull
done

echo "update finished!"
