#!/bin/bash

export WTOOL_DIR=$(dirname "$(echo "$0" | sed -e '')")

# load common lib functions
source $WTOOL_DIR/wtool-common

# load rcfile
rcfile="$WTOOL_DIR/wtoolrc"
[ -r "$rcfile" ] && source "$rcfile"
custom_rcfile="${HOME}/.wtoolrc"
[ -r "$custom_rcfile" ] && source "$custom_rcfile"

# check update
[ "$WTOOL_DAILYCHECK" == "true"  ] && bash $WTOOL_DIR/wtool-check-update & 2>/dev/null

if [ $# = 0 ];then
    logo
    pcolumn 'Usage '
    pcolumn " wtool list\t: show all commands \nwtool command\t: execute a command\nwtool update\t: update wtool\nwtool addmodule\t: add custom module\nwtool rmmodule\t: remove custom module\nwtool uninstall\t: uninstall wtool"
    exit
fi

if [ "$1" = "list" ];then 
    list_module "$@"
fi

if [ "$1" = "addmodule" ]; then
    add_module "$@"
fi

if [ "$1" = "rmmodule" ]; then
    remove_module "$@"
fi

if [ "$1" = "uninstall" ]; then
    uninstall "$@"
fi

tools_dir=$WTOOL_DIR/*/tools/
custom_tools_dir=$WTOOL_DIR/custom/*/tools/
command_file=$1;shift
command=`find $tools_dir -maxdepth 1 -name $command_file `

if [ ! -f "$command" ]; then
    command=`find $custom_tools_dir -maxdepth 1 -name $command_file `
    if [ ! -f "$command" ]; then
	echo "$command_file command not found!"
	exit 1;
    fi
fi

exec "$command" "$@"
